name: Node JS CI/CD
on: [push]

jobs:

   build:

     runs-on: ubuntu-latest

     steps:
     # Checkout.
     - uses: actions/checkout@v1

     # File Check
     - name: Check Files.
       working-directory: my-app
       run: ls -l
       
     - name: Build
       working-directory: my-app
       run: |
          npm build
