name: Node JS CI/CD
on: [push]

jobs:

   build:

     runs-on: ubuntu-latest

     steps:
     # Checkout.
     - uses: actions/checkout@v1

     # File Check.
     - name: Check Files.
       working-directory: my-app
       run: ls -l
       
     - name: npm install, build, and test
       working-directory: my-app
       run: |
         npm install
         npm run build --if-present
         npm test
         ls -l
       env:
         CI: true
      
     - name: zip build file
       working-directory: my-app
       run: |
          cd build && zip -r ../code.zip *
          ls -l
          
     - name: upload to S3
       working-directory: my-app
       env: 
          AWS_ACCESS_KEY_ID: ${{secrets.ac_key}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.sec_key}}
          BUCKET_NAME: ${{secrets.bucket_name}}
          BUCKET_KEY: ${{secrets.bucket_key}}
       run: |
          aws s3 cp code.zip s3://$BUCKET_NAME/$BUCKET_KEY/
          
     - name: Update Lambda
       env: 
          AWS_ACCESS_KEY_ID: ${{secrets.ac_key}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.sec_key}}
       run: |
          aws configure set default.region ap-south-1
          aws lambda update-function-code \
              --function-name  MyTestNodeJS \
              --s3-bucket swarmcluster-statefile \
              --s3-key node/code.zip \
              --region ap-south-1
              
