name: Node JS CI/CD
on: [push]

jobs:

   build:

     runs-on: ubuntu-latest

     steps:
     # Checkout.
     - uses: actions/checkout@v1

     # File Check
     - name: Check Files.
       working-directory: my-app
       run: ls -l
       
     - name: npm install, build, and test
       working-directory: my-app
       run: |
         npm install
         npm run build --if-present
         npm test
       env:
         CI: true
      
     - name: zip build file
       working-directory: my-app
       run: |
          zip code.zip build/
